ALTER TABLE adopciones
ADD COLUMN IF NOT EXISTS activo BOOLEAN DEFAULT TRUE NOT NULL,
ADD COLUMN IF NOT EXISTS fecha_publicacion TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS fecha_actualizacion TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0 NOT NULL;

ALTER TABLE solicitudes_adopcion
ADD COLUMN IF NOT EXISTS motivo_rechazo TEXT,
ADD COLUMN IF NOT EXISTS fecha_solicitud TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS fecha_respuesta TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS fecha_actualizacion TIMESTAMPTZ DEFAULT NOW(),
ADD COLUMN IF NOT EXISTS version BIGINT DEFAULT 0;